### ISSUE TITLE
Вывод последнего expression как в ijavascript 

### ISSUE THREAD

**Issue by obenjiro** [Graphnull/jupnode#1]
```
const tf = require('@tensorflow/tfjs-node-gpu');
tf.backend().isUsingGpuDevice
```

Не выдает ничего, приходится писать

```
const tf = require('@tensorflow/tfjs-node-gpu');
console.log(tf.backend().isUsingGpuDevice)
```

Это не нужно писать в ijavascript (он автоматически выводит последний expression)

**Comment by Graphnull** [comment]
> ```
> const tf = require('@tensorflow/tfjs-node-gpu');
> tf.backend().isUsingGpuDevice
> ```
> 
> Не выдает ничего, приходится писать
> 
> ```
> const tf = require('@tensorflow/tfjs-node-gpu');
> console.log(tf.backend().isUsingGpuDevice)
> ```
> 
> Это не нужно писать в ijavascript (он автоматически выводит последний expression)

Готово. Я добавляю в конец "return" в babel ast. https://github.com/Graphnull/jupnode/blob/044e063f31d2ab5e16782f293ecfb36f2ce24b92/src/transform.js#L18
