### ISSUE TITLE
Не могу разбить код на несколько cell

### ISSUE THREAD

**Issue by obenjiro** [Graphnull/jupnode#2]
<img width="823" alt="Screen Shot 2021-06-01 at 17 21 37" src="https://user-images.githubusercontent.com/1760346/120339636-f0f47880-c2fd-11eb-805b-8b0ccb3e4709.png">

А хотелось бы

**Comment by Graphnull** [comment]
> <img alt="Screen Shot 2021-06-01 at 17 21 37" width="823" src="https://user-images.githubusercontent.com/1760346/120339636-f0f47880-c2fd-11eb-805b-8b0ccb3e4709.png">
> 
> А хотелось бы

Готово. Я добавил babel parser и убираю "var" у переменных находящиеся на верхнем уровне, что бы они писали в глобальную область видимости. https://github.com/Graphnull/jupnode/blob/044e063f31d2ab5e16782f293ecfb36f2ce24b92/src/transform.js#L11
