### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by obenjiro** [Graphnull/jupnode#3]
https://github.com/Graphnull/jupnode/blob/main/jupnode/__init__.py#L31

Лучше вместо вставки 'await () =>' - заменить с помощью babel/parse, babel/trasform который замении все root объявления переменных 

```
const a = 1;
----
console.log(a);
->

(await ()=>
  global.a = 1;
});
----
(await ()=>
  console.log(global.a);
});
```
 
 в случае с https://github.com/n-riesco/ijavascript/commit/bd81728880891c336e801ae3ca8b1e7ae2dd2a5e это делается менее крутым acorn
```
var processTopLevelAwait = require("jp-parser").processTopLevelAwait;<br class="Apple-interchange-newline">
```

Тогда https://github.com/Graphnull/jupnode/issues/2 автоматически исправится

**Comment by Graphnull** [comment]
Вроде сейчас более менее нормально, но const не является глобальной переменной. Стоит ли const делать глобальным?

**Comment by obenjiro** [comment]
Смотри когда я пишу

var a = 1;
//// следующий cell
console.log(a);

let a = 1;
//// следующий cell
console.log(a);

const a = 1;
//// следующий cell
console.log(a);

Я подразумеваю что все это один и тот-же код. Кажется что для все top level vars стоит превращать в Global Vars ибо я просто не смогу нормально разделять код на отдельные cell's и перевыполнять их только там где нужно

И иначе просто все всегда придется писать в 1 cell

Хотеся иногода перевычислить только архитектуру Model, иногда только ее переобучить, а иногда только поменять validation dataset. Без возможности делить код на отдельные cell (как это делается в Python) это будет просто не возможно

**Comment by Graphnull** [comment]
> Смотри когда я пишу
> 
> var a = 1;
> //// следующий cell
> console.log(a);
> 
> let a = 1;
> //// следующий cell
> console.log(a);
> 
> const a = 1;
> //// следующий cell
> console.log(a);
> 
> Я подразумеваю что все это один и тот-же код. Кажется что для все top level vars стоит превращать в Global Vars ибо я просто не смогу нормально разделять код на отдельные cell's и перевыполнять их только там где нужно
> 
> И иначе просто все всегда придется писать в 1 cell
> 
> Хотеся иногода перевычислить только архитектуру Model, иногда только ее переобучить, а иногда только поменять validation dataset. Без возможности делить код на отдельные cell (как это делается в Python) это будет просто не возможно

Я добавил все top level vars как global vars
https://github.com/Graphnull/jupnode/blob/bf54081d6f3472baa419bd8416d58d0bf97ff24e/src/transform.js#L13
