### ISSUE TITLE
Share top-level functions and Classes

### ISSUE THREAD

**Issue by obenjiro** [Graphnull/jupnode#4]
<img width="1444" alt="Screen Shot 2021-06-03 at 15 45 41" src="https://user-images.githubusercontent.com/1760346/120647025-d0a1f680-c482-11eb-9a49-0468bb144a53.png">

**Comment by Graphnull** [comment]
Спасибо за issues. Ща все забабахаем😎

**Comment by Graphnull** [comment]
https://github.com/Graphnull/jupnode/tree/bc12f9e156d160a5a39e9c9cfb12e8481ff19f02
Классы и функции перемещаются в глобальную область
```javascript
let t = 1;
function func(){console.log(2)}
func();
let r = 3;
```
превращается в
```javascript
function func(){console.log(2)}
(async()=>{
  let t = 1;
  func();
  let r = 3;
})()
```
